version: "3.8"
services:
  back-end:
    build:
      context: ./backend-form-application
      dockerfile: Dockerfile
    image: backend-form-application
    ports:
      - 8080:8080
    environment:
      - SPRING.PROFILES.ACTIVE=default
  front-end:
    build:
      context: ./redway-front-end
      dockerfile: Dockerfile
    image: redway-front-end
    container_name: front-end
    ports:
      - 3000:3000
    depends_on:
      - back-end
